steps:
  # Docker Build
  - id: "Build api image 🔨"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_API_IMAGE_NAME}:${_TAG}"
      - "api"
    waitFor:
      - "-"

  - id: "Build front image 🔨"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_FRONT_IMAGE_NAME}:${_TAG}"
      - "front"
    waitFor:
      - "-"

  # Docker Push
  - id: "Push api image to GCP ☁️"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_API_IMAGE_NAME}:${_TAG}"
    waitFor:
      - "Build api image 🔨"

  - id: "Push front image to GCP ☁️"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_FRONT_IMAGE_NAME}:${_TAG}"
    waitFor:
      - "Build front image 🔨"

  # Replace image names in pipeline
  - id: "Replace image name with some black magic 🧙"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: "bash"
    args:
      - "${_CLOUDBUILD_DIR}/envsubst.sh"
      - "${_CLOUDBUILD_DIR}/pipeline.yml"
    env:
      - "_API_IMAGE_FULLNAME=${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_API_IMAGE_NAME}:${_TAG}"
      - "_FRONT_IMAGE_FULLNAME=${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_FRONT_IMAGE_NAME}:${_TAG}"
    waitFor:
      - "-"

  # Recycle depoyment
  - id: "Delete api deployment cause I can ♻️"
    name: "gcr.io/cloud-builders/kubectl"
    args:
      - "delete"
      - "deployment"
      - "${_API_DEPLOYMENT_NAME}"
    env:
      - "CLOUDSDK_COMPUTE_REGION=${_LOCATION}"
      - "CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}"
    waitFor:
      - "Push api image to GCP ☁️"

  - id: "Delete front deployment cause I can ♻️"
    name: "gcr.io/cloud-builders/kubectl"
    args:
      - "delete"
      - "deployment"
      - "${_FRONT_DEPLOYMENT_NAME}"
    env:
      - "CLOUDSDK_COMPUTE_REGION=${_LOCATION}"
      - "CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}"
    waitFor:
      - "Push front image to GCP ☁️"

  # Deploy kubernetes ressources to GKE
  - id: "Apply deployments 🚀"
    name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=${_CLOUDBUILD_DIR}/pipeline.yml
      - --location=${_LOCATION}
      - --cluster=${_CLUSTER_NAME}

timeout: 1200s

substitutions:
  _CLOUDBUILD_DIR: kubernetes/cloudbuild
  _CLUSTER_NAME: pr-ftw-cluster
  _LOCATION: europe-west1
  _ARTIFACT_REPO: pr-ftw-repo
  _API_IMAGE_NAME: time-manager-api
  _API_DEPLOYMENT_NAME: api-deployment
  _FRONT_IMAGE_NAME: time-manager-front
  _FRONT_DEPLOYMENT_NAME: front-deployment
  _TAG: "1.0"
