version: '3'

services:
  front:
    build:
      context: front
    image: time-manager-front
    environment:
      API_HOST: localhost
      API_PORT: 4000
    ports:
      - 80:80
    depends_on:
      - api

  api:
    build:
      context: api
    image: time-manager-api
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: time_manager
      PGPORT: 5432
      PGHOST: postgresql
    ports:
      - 4000:4000
    depends_on:
      - postgresql

  postgresql:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    restart: always
    volumes:
      - '/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock'
      - 'dbdata:/var/lib/postgresql/data'

volumes:
  dbdata:
