apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: europe-west1-docker.pkg.dev/timemanager-330510/pr-ftw-repo/time-manager-api:1.0
          ports:
            - containerPort: 4000
          env:
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: psql-secret
                  key: psql-username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: psql-secret
                  key: psql-password
            - name: PGDATABASE
              valueFrom:
                configMapKeyRef:
                  name: psql-config
                  key: psql-database
            - name: PGPORT
              valueFrom:
                configMapKeyRef:
                  name: psql-config
                  key: psql-port
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  name: psql-config
                  key: psql-host
          resources:
            requests:
              memory: 512Mi
              cpu: 125m
            limits:
              memory: 512Mi
              cpu: 250m
